{% set name = "pydantic-openapi-schema" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_openapi_schema-{{ version }}.tar.gz
  sha256: d9b56235f4c4817c6e3693c4f8122c3e5e9c75f6b3b454524ad985012a264daf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - email-validator
    - pydantic >=1.10.0

test:
  imports:
    - pydantic_openapi_schema
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/starlite-api/pydantic-openapi-schema
  doc_url: https://starlite-api.github.io/pydantic-openapi-schema/
  summary: OpenAPI Schema using pydantic. Forked for Starlite-API from 'openapi-schema-pydantic'.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
